clone:
  drone-demo.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy

pipeline:
  build:
    image: index.qiniu.com/spock/golang:1.7
    pull: true
    commands:
      - source env.sh
      - echo $TEST_ENV
      - make build
      - make test
